version: '3'

services:
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: main
      POSTGRES_DB: root
    ports: [5432]
    network_mode: "host"
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0